spring.datasource.url=jdbc:postgresql://localhost:5432/applypilot
spring.datasource.username=postgres
spring.datasource.password=Project@1928

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=health,info